export interface PostMeta {
  slug: string;
  title: string;
  description: string;
  date: string;
  readingMinutes: number;
  keywords: string[];
}

export const posts: PostMeta[] = [
  {
    slug: "google-play-12-testers-guide",
    title: "Google Play 12 Testers for 14 Days: The Complete 2026 Guide",
    description:
      "Everything indie Android devs need to meet Google Play's 12-tester / 14-day closed-testing requirement — what 'active' means, common failure modes, and how to find real testers fast.",
    date: "2026-06-06",
    readingMinutes: 9,
    keywords: ["google play 12 testers", "12 testers 14 days", "google play closed testing", "google play production access", "android beta testers"],
  },
  {
    slug: "find-12-testers-24-hours",
    title: "How to Find 12 Google Play Testers in 24 Hours",
    description: "The fastest legitimate ways to round up 12 active testers for Google Play closed testing — without paying for sketchy Fiverr accounts.",
    date: "2026-06-03",
    readingMinutes: 4,
    keywords: ["find 12 google play testers fast", "google play testers in 24 hours", "fastest way to get android testers"],
  },
  {
    slug: "what-counts-as-active-tester",
    title: "What Counts as an Active Tester on Google Play?",
    description: "Google doesn't publish a strict definition. Here's the working rule for what counts toward the 12 active testers Google Play requires.",
    date: "2026-06-01",
    readingMinutes: 3,
    keywords: ["active tester google play", "what counts as active tester", "google play tester definition"],
  },
  {
    slug: "not-enough-testers-after-14-days",
    title: "Play Console Says 'Not Enough Testers' After 14 Days — Why",
    description: "You think you had 12 testers for 14 days, but Play Console disagrees. Here are the five reasons the count came up short, and how to fix each one.",
    date: "2026-05-28",
    readingMinutes: 5,
    keywords: ["not enough testers google play", "play console 14 days not enough testers", "google play tester count wrong"],
  },
  {
    slug: "closed-vs-internal-vs-open-testing",
    title: "Closed Testing vs Internal Testing vs Open Testing on Google Play",
    description: "The three Google Play testing tracks have different rules, audiences, and limits. Here's when to use each — and which one counts toward production access.",
    date: "2026-05-25",
    readingMinutes: 4,
    keywords: ["closed testing vs internal testing", "google play testing tracks", "open testing google play", "internal vs closed test"],
  },
  {
    slug: "own-google-accounts-as-testers",
    title: "Can I Use My Own Google Accounts as Testers? (Spoiler: No)",
    description: "Why stacking your own burner Google accounts as testers backfires — and what Google's anti-abuse system actually catches.",
    date: "2026-05-22",
    readingMinutes: 3,
    keywords: ["own google accounts as testers", "burner accounts google play", "fake testers google play"],
  },
  {
    slug: "google-play-20-to-12-rule-change",
    title: "20 to 12: Google Play's Tester Rule Change Explained",
    description: "Google dropped the closed-testing requirement from 20 testers to 12 in 2024. Here's what changed, what didn't, and who it helps.",
    date: "2026-05-20",
    readingMinutes: 3,
    keywords: ["google play 20 to 12 testers", "tester rule change 2024", "google play rule change"],
  },
  {
    slug: "personal-vs-organization-account-testing",
    title: "Personal vs Organization Google Play Accounts: Testing Rules",
    description: "Only personal accounts created after Nov 2023 face the 12-tester gate. Here's how organization accounts differ — and whether converting is worth it.",
    date: "2026-05-17",
    readingMinutes: 4,
    keywords: ["personal vs organization google play account", "play console account types", "organization account testing"],
  },
  {
    slug: "does-internal-testing-count",
    title: "Does Internal Testing Count Toward the 12-Tester Requirement?",
    description: "Short answer: no. Long answer: here's why Google only counts closed testing, and what to do if you've been on the wrong track.",
    date: "2026-05-14",
    readingMinutes: 3,
    keywords: ["does internal testing count", "internal testing 12 testers", "closed testing required"],
  },
  {
    slug: "tester-uninstalls-during-14-days",
    title: "A Tester Uninstalled on Day 10. Did My 14-Day Timer Reset?",
    description: "What actually happens when a tester drops out mid-window, how Google's counter behaves, and how to buffer your tester pool to avoid restarts.",
    date: "2026-05-11",
    readingMinutes: 3,
    keywords: ["tester uninstalled 14 day timer", "14 day timer reset google play", "tester dropped out"],
  },
  {
    slug: "setup-closed-testing-track-step-by-step",
    title: "How to Set Up a Google Play Closed Testing Track (Step by Step)",
    description: "Click-by-click Play Console walkthrough for creating a closed testing track, uploading your bundle, and sharing the opt-in URL with testers.",
    date: "2026-05-08",
    readingMinutes: 6,
    keywords: ["set up closed testing google play", "play console closed test setup", "create closed testing track"],
  },
  {
    slug: "tester-briefing-email-template",
    title: "A Tester Briefing Email That Gets People to Actually Test",
    description: "Most tester emails get ignored. Here's a short, copy-paste-ready template that explains the opt-in flow and the 14-day commitment.",
    date: "2026-05-05",
    readingMinutes: 3,
    keywords: ["tester briefing email", "google play tester invitation", "email template testers"],
  },
  {
    slug: "find-testers-target-country",
    title: "How to Find Google Play Testers in a Specific Country",
    description: "GDPR, INR pricing, or simply a regional launch — sometimes you need testers from a specific country. Here's where to look.",
    date: "2026-05-02",
    readingMinutes: 4,
    keywords: ["google play testers by country", "find testers india", "testers eu gdpr", "regional android testers"],
  },
  {
    slug: "find-testers-on-reddit",
    title: "How to Find Google Play Testers on Reddit (Without Getting Banned)",
    description: "r/AndroidDev and r/TestersCommunity can deliver testers fast — if you follow the unwritten rules. Here they are.",
    date: "2026-04-29",
    readingMinutes: 4,
    keywords: ["reddit android testers", "find testers reddit", "r/androiddev testers"],
  },
  {
    slug: "find-testers-on-discord",
    title: "How to Find Android Beta Testers on Discord",
    description: "Several indie Android dev Discord servers run weekly tester-swap threads. Here are the ones worth joining and how to participate without burning out.",
    date: "2026-04-26",
    readingMinutes: 3,
    keywords: ["discord android testers", "find testers discord", "indie dev discord beta testing"],
  },
  {
    slug: "monitor-active-tester-count",
    title: "How to Monitor Your Active Tester Count in Play Console",
    description: "Where exactly the active-tester count lives in Play Console, how often it updates, and what to watch for so you don't fail the 14-day window.",
    date: "2026-04-23",
    readingMinutes: 3,
    keywords: ["monitor tester count play console", "active tester report", "play console tester dashboard"],
  },
  {
    slug: "invite-testers-closed-testing",
    title: "How to Invite Testers to Google Play Closed Testing",
    description: "Email lists, Google Groups, and opt-in URLs — the three ways to invite testers to your closed track, plus which one Google actually recommends.",
    date: "2026-04-20",
    readingMinutes: 4,
    keywords: ["invite testers closed testing", "google play tester invite", "opt-in url google play"],
  },
  {
    slug: "extend-closed-testing-after-production",
    title: "Should You Keep Closed Testing Running After Going Live?",
    description: "Once you've shipped to production, do you need to keep the closed track active? Here's what changes — and what doesn't.",
    date: "2026-04-17",
    readingMinutes: 3,
    keywords: ["closed testing after production", "keep closed test active", "post-launch testing"],
  },
  {
    slug: "recover-from-dropped-testers",
    title: "How to Recover When You Drop Below 12 Active Testers",
    description: "Day 11, one tester just uninstalled, you're at 11. Here's the recovery playbook — and what Google actually does with the reset.",
    date: "2026-04-14",
    readingMinutes: 4,
    keywords: ["dropped below 12 testers", "recover lost testers", "tester pool recovery"],
  },
  {
    slug: "recruit-testers-niche-apps",
    title: "How to Recruit Testers for Niche Apps With Small Audiences",
    description: "When your app is built for, say, fish photographers in Norway, the broad Reddit threads won't help. Here's how to source niche testers.",
    date: "2026-04-11",
    readingMinutes: 4,
    keywords: ["recruit testers niche app", "small audience beta testers", "vertical app testers"],
  },
  {
    slug: "betafamily-vs-apptest",
    title: "BetaFamily vs AppTest for the Google Play 12-Tester Rule",
    description: "BetaFamily is a great crowd-testing platform but wasn't built for the 12-tester gate. Here's the honest comparison for indie Android devs.",
    date: "2026-04-08",
    readingMinutes: 4,
    keywords: ["betafamily vs apptest", "beta family alternative", "google play tester platform comparison"],
  },
  {
    slug: "primetestlab-vs-mutual-testing",
    title: "PrimeTestLab vs Free Mutual Testing: Real Cost Comparison",
    description: "Paying $15–30 for 12 testers is convenient. Mutual swaps are free but take time. Here's the real cost-benefit for indie devs.",
    date: "2026-04-05",
    readingMinutes: 4,
    keywords: ["primetestlab alternative", "paid vs free testers", "mutual testing comparison"],
  },
  {
    slug: "paid-google-play-testers-worth-it",
    title: "Are Paid Google Play Testers Worth It?",
    description: "What you actually get for $15–50, the risks Google won't refund you for, and when paying is genuinely the right call.",
    date: "2026-04-02",
    readingMinutes: 4,
    keywords: ["paid google play testers", "buy testers worth it", "tester service review"],
  },
  {
    slug: "fiverr-testers-rejected",
    title: "Why Fiverr Testers Get Your Google Play App Rejected",
    description: "Cheap Fiverr tester gigs often use accounts Google has already flagged. Here's how that breaks your 14-day cohort and what to do instead.",
    date: "2026-03-30",
    readingMinutes: 3,
    keywords: ["fiverr testers google play", "fake tester accounts rejected", "fiverr beta testing risk"],
  },
  {
    slug: "free-vs-paid-12-testers",
    title: "Free vs Paid Ways to Get 12 Google Play Testers",
    description: "Side-by-side breakdown of free mutual-testing communities, paid services, and bring-your-own audiences. Pick what fits your timeline.",
    date: "2026-03-27",
    readingMinutes: 5,
    keywords: ["free google play testers", "paid testers comparison", "12 testers cost"],
  },
  {
    slug: "testflight-vs-closed-testing",
    title: "TestFlight vs Google Play Closed Testing: What's Different",
    description: "If you're crossing over from iOS, here's why Google Play closed testing surprises you — and what TestFlight habits to unlearn.",
    date: "2026-03-24",
    readingMinutes: 4,
    keywords: ["testflight vs google play", "ios vs android beta testing", "closed testing differences"],
  },
  {
    slug: "usertesting-vs-mutual-testing",
    title: "UserTesting vs Mutual Testing for Android Apps",
    description: "UserTesting and similar platforms are great for UX research, terrible for the 12-tester gate. Here's why and what to use instead.",
    date: "2026-03-21",
    readingMinutes: 3,
    keywords: ["usertesting android alternative", "ux research vs beta testing", "user research vs closed testing"],
  },
  {
    slug: "how-mutual-testing-reciprocity-works",
    title: "How Mutual Testing Reciprocity Actually Works",
    description: "Why developer swap communities outperform paid platforms for the 12-tester rule: everyone has the same problem, so everyone shows up.",
    date: "2026-03-18",
    readingMinutes: 3,
    keywords: ["mutual testing how it works", "swap testing reciprocity", "developer exchange"],
  },
  {
    slug: "fix-not-enough-testers-error",
    title: "Fix the 'Not Enough Testers' Error in Play Console",
    description: "Five concrete fixes for the 'Not enough testers' message, in order from most-to-least common.",
    date: "2026-03-15",
    readingMinutes: 4,
    keywords: ["not enough testers error", "play console error fix", "tester count error"],
  },
  {
    slug: "closed-testing-rejected-fixes",
    title: "Google Play Rejected My Closed Testing — Now What?",
    description: "Closed-testing rejections are rare but real. Here's the appeal process, what to fix first, and how long re-review takes.",
    date: "2026-03-12",
    readingMinutes: 4,
    keywords: ["closed testing rejected", "google play rejection appeal", "fix testing rejection"],
  },
  {
    slug: "14-day-timer-reset-causes",
    title: "Why Your Google Play 14-Day Timer Just Reset",
    description: "The five things that quietly reset the 14-day counter — most of them invisible until production access stays locked.",
    date: "2026-03-09",
    readingMinutes: 4,
    keywords: ["14 day timer reset", "google play counter reset", "closed testing timer"],
  },
  {
    slug: "testing-track-stuck-troubleshooting",
    title: "Google Play Closed Testing Track Stuck: Troubleshooting Guide",
    description: "Your build is uploaded, testers are opted in, but the track shows zero activity. Walk through the seven most common causes.",
    date: "2026-03-06",
    readingMinutes: 5,
    keywords: ["closed testing stuck", "play console troubleshooting", "testing track not working"],
  },
  {
    slug: "tester-not-showing-active",
    title: "A Tester Accepted the Invite But Isn't Showing as Active",
    description: "The most common silent failure: a tester opted in, installed the app, and is still listed as inactive. Here are the four reasons and the fixes.",
    date: "2026-03-03",
    readingMinutes: 4,
    keywords: ["tester not active", "tester accepted but inactive", "google play tester invisible"],
  },
  {
    slug: "production-access-denied",
    title: "Google Play Production Access Denied After Closed Testing",
    description: "You did your 14 days and Google still won't grant production access. Here's how to read the rejection and what to fix.",
    date: "2026-02-28",
    readingMinutes: 4,
    keywords: ["production access denied", "google play production rejected", "after closed testing"],
  },
  {
    slug: "closed-testing-review-time",
    title: "How Long Does Google Play Closed Testing Review Take?",
    description: "Closed-testing review timelines have changed in 2026. Here's what to expect for your first review vs subsequent updates.",
    date: "2026-02-25",
    readingMinutes: 3,
    keywords: ["closed testing review time", "google play review duration", "how long closed test review"],
  },
  {
    slug: "common-closed-testing-mistakes",
    title: "8 Common Closed Testing Mistakes Indie Devs Make",
    description: "Most failures aren't bugs in your app — they're process mistakes. Here are the eight that send devs back to day 1 of the 14-day window.",
    date: "2026-02-22",
    readingMinutes: 5,
    keywords: ["common closed testing mistakes", "play console mistakes", "indie dev testing errors"],
  },
  {
    slug: "pre-launch-android-checklist",
    title: "Pre-Launch Android App Checklist for Indie Developers",
    description: "Everything to nail before you start the 14-day closed-testing clock — privacy policy, content rating, target SDK, screenshots, more.",
    date: "2026-02-19",
    readingMinutes: 5,
    keywords: ["pre-launch android checklist", "indie dev launch checklist", "play store launch prep"],
  },
  {
    slug: "validate-android-app-idea",
    title: "How to Validate Your Android App Idea Before Closed Testing",
    description: "Closed testing isn't validation — it's a publishing gate. Here's how to validate cheaply before you spend 14 days waiting.",
    date: "2026-02-16",
    readingMinutes: 4,
    keywords: ["validate android app idea", "indie app validation", "market test android"],
  },
  {
    slug: "indie-android-marketing-first-100",
    title: "Indie Android Dev Marketing: Getting Your First 100 Users",
    description: "Past the 12-tester gate, into production — now what? A no-budget marketing playbook tuned for indie Android devs.",
    date: "2026-02-13",
    readingMinutes: 6,
    keywords: ["indie android marketing", "first 100 users android", "post-launch growth"],
  },
  {
    slug: "play-store-description-converts",
    title: "Write a Play Store Description That Converts",
    description: "Anatomy of a high-converting Play Store listing — short description, long description, keyword density, and the mistake 80% of devs make.",
    date: "2026-02-10",
    readingMinutes: 5,
    keywords: ["play store description converts", "aso description", "google play listing"],
  },
  {
    slug: "android-screenshots-drive-installs",
    title: "Android Screenshots That Drive Installs",
    description: "Your first three screenshots do 80% of the conversion work. Here's how to structure them for maximum install rate.",
    date: "2026-02-07",
    readingMinutes: 4,
    keywords: ["android screenshots install rate", "play store screenshots", "aso screenshots"],
  },
  {
    slug: "indie-android-community-guide",
    title: "The Indie Android Dev Community Guide",
    description: "Every active Reddit, Discord, X account, and newsletter worth following as an indie Android dev in 2026.",
    date: "2026-02-04",
    readingMinutes: 5,
    keywords: ["indie android community", "android dev community", "android developer resources"],
  },
  {
    slug: "closed-to-production-timeline",
    title: "From Closed Testing to Production: The Full Google Play Timeline",
    description: "Day-by-day timeline of going from a new personal account to a live app in production, with realistic buffers.",
    date: "2026-02-01",
    readingMinutes: 5,
    keywords: ["closed testing to production timeline", "google play launch timeline", "play store launch days"],
  },
  {
    slug: "android-on-a-budget",
    title: "Building an Android App on a Budget: Tools and Resources",
    description: "Free and cheap tools that cover everything from design to analytics — the indie Android stack that costs under $20/month.",
    date: "2026-01-29",
    readingMinutes: 5,
    keywords: ["android app budget", "indie android tools", "free android dev tools"],
  },
  {
    slug: "play-console-personal-account-requirements",
    title: "Google Play Personal Account Requirements Explained",
    description: "ID verification, address checks, the 12-tester rule — everything that gates a new personal Play Console account.",
    date: "2026-01-26",
    readingMinutes: 4,
    keywords: ["personal play console requirements", "personal account verification", "play console kyc"],
  },
  {
    slug: "google-play-policy-changes-2026",
    title: "Google Play Developer Policy Changes 2026",
    description: "Every meaningful Play policy change in 2026 that affects indie devs — and what action each one demands.",
    date: "2026-01-23",
    readingMinutes: 6,
    keywords: ["google play policy changes 2026", "play console policy update", "android policy changes"],
  },
  {
    slug: "testing-requirements-new-accounts",
    title: "App Testing Requirements for New Play Console Accounts",
    description: "The official Google testing requirements for new accounts in plain English, with the parts most devs misread highlighted.",
    date: "2026-01-20",
    readingMinutes: 4,
    keywords: ["testing requirements new accounts", "play console new account rules", "android testing requirements"],
  },
  {
    slug: "production-access-criteria",
    title: "Google Play Production Access Criteria",
    description: "What Google actually checks before granting production access, beyond the 12 testers / 14 days — and how to pre-clear each.",
    date: "2026-01-17",
    readingMinutes: 4,
    keywords: ["production access criteria", "google play production checklist", "play store production approval"],
  },
  {
    slug: "closed-testing-data-collected",
    title: "What Data Does Google Collect During Closed Testing?",
    description: "What Google tracks about your testers, what testers see about your app, and what privacy implications you need to disclose.",
    date: "2026-01-14",
    readingMinutes: 4,
    keywords: ["closed testing data collected", "google play tester data", "beta testing privacy"],
  },
  {
    slug: "privacy-requirements-beta-testing",
    title: "Privacy Requirements for Android Beta Testing",
    description: "Your privacy policy needs to cover beta testing too. Here's what's required, what's optional, and a copy-paste clause that satisfies Play review.",
    date: "2026-01-11",
    readingMinutes: 4,
    keywords: ["privacy beta testing", "android privacy policy", "play store privacy testing"],
  },
];

export const getPost = (slug: string): PostMeta | undefined =>
  posts.find((p) => p.slug === slug);
